# Generated by Django 3.1.5 on 2021-01-15 00:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/images')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(help_text='Enter the name of the dish.', max_length=75)),
                ('description', models.CharField(help_text='Enter a description of the dish.', max_length=450)),
                ('cost', models.DecimalField(decimal_places=2, help_text='Enter the cost of the dish', max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='TruckInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the store name.', max_length=75)),
                ('location', models.CharField(help_text='Enter the current location.', max_length=75)),
                ('contact', models.IntegerField(blank=True, help_text='Enter a working number for the truck.', max_length=10)),
                ('images', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='truck.album')),
                ('menu', models.ManyToManyField(to='truck.MenuItem')),
                ('owner', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', 'owner', 'location'],
            },
        ),
        migrations.AddField(
            model_name='album',
            name='album',
            field=models.ManyToManyField(to='truck.Image'),
        ),
    ]
