# Generated by Django 3.1.5 on 2021-01-15 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truckinstance',
            name='contact',
            field=models.IntegerField(blank=True, help_text='Enter a working number for the truck.'),
        ),
    ]
