# Generated by Django 3.1.5 on 2021-01-15 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck', '0002_auto_20210115_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_name',
            field=models.CharField(default=1, help_text='Enter the albums name.', max_length=75),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='truckinstance',
            name='contact',
            field=models.CharField(blank=True, help_text='Enter a working number for the truck.', max_length=18),
        ),
    ]
