# Generated by Django 3.1.5 on 2021-01-15 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck', '0004_image_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truckinstance',
            name='images',
        ),
        migrations.AddField(
            model_name='truckinstance',
            name='album',
            field=models.ManyToManyField(to='truck.Image'),
        ),
        migrations.DeleteModel(
            name='Album',
        ),
    ]
