# Generated by Django 3.1.5 on 2021-01-19 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck', '0005_auto_20210115_0433'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='What is the pictures name.', max_length=75)),
                ('link', models.URLField(help_text='Enter the target URL.', max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AlterField(
            model_name='truckinstance',
            name='album',
            field=models.ManyToManyField(to='truck.ImageLink'),
        ),
    ]
