# Generated by Django 3.1.5 on 2021-01-21 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck', '0008_orderinstance_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truckinstance',
            name='album',
            field=models.ManyToManyField(blank=True, to='truck.ImageLink'),
        ),
        migrations.AlterField(
            model_name='truckinstance',
            name='location',
            field=models.CharField(default='', help_text='Enter the current location.', max_length=75),
        ),
        migrations.AlterField(
            model_name='truckinstance',
            name='menu',
            field=models.ManyToManyField(blank=True, to='truck.MenuItem'),
        ),
    ]
