# Generated by Django 3.1.5 on 2021-01-21 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck', '0009_auto_20210121_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinstance',
            name='inventory',
            field=models.ManyToManyField(blank=True, to='truck.MenuItem'),
        ),
    ]
