# Generated by Django 3.1.5 on 2021-01-21 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck', '0010_auto_20210121_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagelink',
            name='title',
            field=models.CharField(blank=True, help_text='What is the pictures name.', max_length=75),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='description',
            field=models.CharField(default='No description given.', help_text='Enter a description of the dish.', max_length=450),
        ),
        migrations.AlterField(
            model_name='truckinstance',
            name='location',
            field=models.CharField(default='Closed', help_text='Enter the current location.', max_length=75),
        ),
    ]
