# Generated by Django 3.1.5 on 2021-01-21 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck', '0013_auto_20210121_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinstance',
            name='prepared',
            field=models.BooleanField(default=False),
        ),
    ]
